((jai-ts-mode . ((compile-all-cmd . "c:/Users/Chris/git/jai/handmade_jai/make.bat")
                 (defualt-compile-cmd . "jai c:/Users/Chris/git/jai/handmade_jai/build_handmade.jai")
                 (custom-run-all-cmd . "c:/Users/Chris/git/jai/handmade_jai/build/handmade.exe")
                 (custom-run-test-cmd . "c:/Users/Chris/git/jai/handmade_jai/build/handmade.exe test")
                 (file-to-compile-cmd . (("win32_handmade.jai" . (compile "jai c:/Users/Chris/git/jai/handmade_jai/build_win32_handmade.jai")))))))
